<?php
/**
 * CashFlowAnalyticsMetrics
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Open Banking
 *
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.16.1
 * Contact: apisupport@mastercard.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CashFlowAnalyticsMetrics Class Doc Comment
 *
 * @category Class
 * @description Cash flow analytics metrics and calculations
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CashFlowAnalyticsMetrics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CashFlowAnalyticsMetrics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'inflow' => '\OpenAPI\Client\Model\CashFlowInflowAttributes',
        'negative_triggers' => '\OpenAPI\Client\Model\CashFlowNegativeTriggers',
        'outflow' => '\OpenAPI\Client\Model\CashFlowOutflowAttributes',
        'revenue_by_month_for_the_report_time_period' => '\OpenAPI\Client\Model\ObbDateRangeAndAmount[]',
        'revenue_for_the_report_time_period' => 'float',
        'transaction_analytics' => '\OpenAPI\Client\Model\CashFlowTransactionAnalyticsAttributes'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'inflow' => null,
        'negative_triggers' => null,
        'outflow' => null,
        'revenue_by_month_for_the_report_time_period' => null,
        'revenue_for_the_report_time_period' => null,
        'transaction_analytics' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'inflow' => false,
        'negative_triggers' => false,
        'outflow' => false,
        'revenue_by_month_for_the_report_time_period' => false,
        'revenue_for_the_report_time_period' => false,
        'transaction_analytics' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'inflow' => 'inflow',
        'negative_triggers' => 'negativeTriggers',
        'outflow' => 'outflow',
        'revenue_by_month_for_the_report_time_period' => 'revenueByMonthForTheReportTimePeriod',
        'revenue_for_the_report_time_period' => 'revenueForTheReportTimePeriod',
        'transaction_analytics' => 'transactionAnalytics'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'inflow' => 'setInflow',
        'negative_triggers' => 'setNegativeTriggers',
        'outflow' => 'setOutflow',
        'revenue_by_month_for_the_report_time_period' => 'setRevenueByMonthForTheReportTimePeriod',
        'revenue_for_the_report_time_period' => 'setRevenueForTheReportTimePeriod',
        'transaction_analytics' => 'setTransactionAnalytics'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'inflow' => 'getInflow',
        'negative_triggers' => 'getNegativeTriggers',
        'outflow' => 'getOutflow',
        'revenue_by_month_for_the_report_time_period' => 'getRevenueByMonthForTheReportTimePeriod',
        'revenue_for_the_report_time_period' => 'getRevenueForTheReportTimePeriod',
        'transaction_analytics' => 'getTransactionAnalytics'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('inflow', $data ?? [], null);
        $this->setIfExists('negative_triggers', $data ?? [], null);
        $this->setIfExists('outflow', $data ?? [], null);
        $this->setIfExists('revenue_by_month_for_the_report_time_period', $data ?? [], null);
        $this->setIfExists('revenue_for_the_report_time_period', $data ?? [], null);
        $this->setIfExists('transaction_analytics', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets inflow
     *
     * @return \OpenAPI\Client\Model\CashFlowInflowAttributes|null
     */
    public function getInflow()
    {
        return $this->container['inflow'];
    }

    /**
     * Sets inflow
     *
     * @param \OpenAPI\Client\Model\CashFlowInflowAttributes|null $inflow inflow
     *
     * @return self
     */
    public function setInflow($inflow)
    {
        if (is_null($inflow)) {
            throw new \InvalidArgumentException('non-nullable inflow cannot be null');
        }
        $this->container['inflow'] = $inflow;

        return $this;
    }

    /**
     * Gets negative_triggers
     *
     * @return \OpenAPI\Client\Model\CashFlowNegativeTriggers|null
     */
    public function getNegativeTriggers()
    {
        return $this->container['negative_triggers'];
    }

    /**
     * Sets negative_triggers
     *
     * @param \OpenAPI\Client\Model\CashFlowNegativeTriggers|null $negative_triggers negative_triggers
     *
     * @return self
     */
    public function setNegativeTriggers($negative_triggers)
    {
        if (is_null($negative_triggers)) {
            throw new \InvalidArgumentException('non-nullable negative_triggers cannot be null');
        }
        $this->container['negative_triggers'] = $negative_triggers;

        return $this;
    }

    /**
     * Gets outflow
     *
     * @return \OpenAPI\Client\Model\CashFlowOutflowAttributes|null
     */
    public function getOutflow()
    {
        return $this->container['outflow'];
    }

    /**
     * Sets outflow
     *
     * @param \OpenAPI\Client\Model\CashFlowOutflowAttributes|null $outflow outflow
     *
     * @return self
     */
    public function setOutflow($outflow)
    {
        if (is_null($outflow)) {
            throw new \InvalidArgumentException('non-nullable outflow cannot be null');
        }
        $this->container['outflow'] = $outflow;

        return $this;
    }

    /**
     * Gets revenue_by_month_for_the_report_time_period
     *
     * @return \OpenAPI\Client\Model\ObbDateRangeAndAmount[]|null
     */
    public function getRevenueByMonthForTheReportTimePeriod()
    {
        return $this->container['revenue_by_month_for_the_report_time_period'];
    }

    /**
     * Sets revenue_by_month_for_the_report_time_period
     *
     * @param \OpenAPI\Client\Model\ObbDateRangeAndAmount[]|null $revenue_by_month_for_the_report_time_period Sum of all transactions categorized as revenue, split by months
     *
     * @return self
     */
    public function setRevenueByMonthForTheReportTimePeriod($revenue_by_month_for_the_report_time_period)
    {
        if (is_null($revenue_by_month_for_the_report_time_period)) {
            throw new \InvalidArgumentException('non-nullable revenue_by_month_for_the_report_time_period cannot be null');
        }
        $this->container['revenue_by_month_for_the_report_time_period'] = $revenue_by_month_for_the_report_time_period;

        return $this;
    }

    /**
     * Gets revenue_for_the_report_time_period
     *
     * @return float|null
     */
    public function getRevenueForTheReportTimePeriod()
    {
        return $this->container['revenue_for_the_report_time_period'];
    }

    /**
     * Sets revenue_for_the_report_time_period
     *
     * @param float|null $revenue_for_the_report_time_period Sum of all transactions categorized as revenue
     *
     * @return self
     */
    public function setRevenueForTheReportTimePeriod($revenue_for_the_report_time_period)
    {
        if (is_null($revenue_for_the_report_time_period)) {
            throw new \InvalidArgumentException('non-nullable revenue_for_the_report_time_period cannot be null');
        }
        $this->container['revenue_for_the_report_time_period'] = $revenue_for_the_report_time_period;

        return $this;
    }

    /**
     * Gets transaction_analytics
     *
     * @return \OpenAPI\Client\Model\CashFlowTransactionAnalyticsAttributes|null
     */
    public function getTransactionAnalytics()
    {
        return $this->container['transaction_analytics'];
    }

    /**
     * Sets transaction_analytics
     *
     * @param \OpenAPI\Client\Model\CashFlowTransactionAnalyticsAttributes|null $transaction_analytics transaction_analytics
     *
     * @return self
     */
    public function setTransactionAnalytics($transaction_analytics)
    {
        if (is_null($transaction_analytics)) {
            throw new \InvalidArgumentException('non-nullable transaction_analytics cannot be null');
        }
        $this->container['transaction_analytics'] = $transaction_analytics;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


