<?php
/**
 * CustomerAccountDetailTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Open Banking
 *
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.16.1
 * Contact: apisupport@mastercard.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CustomerAccountDetailTest Class Doc Comment
 *
 * @category    Class
 * @description Additional customer account details. Not all data points will return for each account type. You can see the account type that each data point will return for in descriptions. The data point are also subject to availability by the institution.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CustomerAccountDetailTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CustomerAccountDetail"
     */
    public function testCustomerAccountDetail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "date_as_of"
     */
    public function testPropertyDateAsOf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "available_balance_amount"
     */
    public function testPropertyAvailableBalanceAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "open_date"
     */
    public function testPropertyOpenDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "period_start_date"
     */
    public function testPropertyPeriodStartDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "period_end_date"
     */
    public function testPropertyPeriodEndDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "period_interest_rate"
     */
    public function testPropertyPeriodInterestRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "period_deposit_amount"
     */
    public function testPropertyPeriodDepositAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "period_interest_amount"
     */
    public function testPropertyPeriodInterestAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "interest_ytd_amount"
     */
    public function testPropertyInterestYtdAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "interest_prior_ytd_amount"
     */
    public function testPropertyInterestPriorYtdAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "maturity_date"
     */
    public function testPropertyMaturityDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "interest_rate"
     */
    public function testPropertyInterestRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credit_available_amount"
     */
    public function testPropertyCreditAvailableAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credit_max_amount"
     */
    public function testPropertyCreditMaxAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cash_advance_available_amount"
     */
    public function testPropertyCashAdvanceAvailableAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cash_advance_max_amount"
     */
    public function testPropertyCashAdvanceMaxAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cash_advance_balance"
     */
    public function testPropertyCashAdvanceBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cash_advance_interest_rate"
     */
    public function testPropertyCashAdvanceInterestRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "current_balance"
     */
    public function testPropertyCurrentBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_min_amount"
     */
    public function testPropertyPaymentMinAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_due_date"
     */
    public function testPropertyPaymentDueDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "previous_balance"
     */
    public function testPropertyPreviousBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statement_start_date"
     */
    public function testPropertyStatementStartDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statement_end_date"
     */
    public function testPropertyStatementEndDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statement_purchase_amount"
     */
    public function testPropertyStatementPurchaseAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statement_finance_amount"
     */
    public function testPropertyStatementFinanceAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statement_credit_amount"
     */
    public function testPropertyStatementCreditAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reward_earned_balance"
     */
    public function testPropertyRewardEarnedBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "past_due_amount"
     */
    public function testPropertyPastDueAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_payment_amount"
     */
    public function testPropertyLastPaymentAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_payment_date"
     */
    public function testPropertyLastPaymentDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statement_close_balance"
     */
    public function testPropertyStatementCloseBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "term_of_ml"
     */
    public function testPropertyTermOfMl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ml_holder_name"
     */
    public function testPropertyMlHolderName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "late_fee_amount"
     */
    public function testPropertyLateFeeAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payoff_amount"
     */
    public function testPropertyPayoffAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payoff_amount_date"
     */
    public function testPropertyPayoffAmountDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "original_maturity_date"
     */
    public function testPropertyOriginalMaturityDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "principal_balance"
     */
    public function testPropertyPrincipalBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "escrow_balance"
     */
    public function testPropertyEscrowBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "interest_period"
     */
    public function testPropertyInterestPeriod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "initial_ml_amount"
     */
    public function testPropertyInitialMlAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "initial_ml_date"
     */
    public function testPropertyInitialMlDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "next_payment_principal_amount"
     */
    public function testPropertyNextPaymentPrincipalAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "next_payment_interest_amount"
     */
    public function testPropertyNextPaymentInterestAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "next_payment"
     */
    public function testPropertyNextPayment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "next_payment_date"
     */
    public function testPropertyNextPaymentDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_payment_due_date"
     */
    public function testPropertyLastPaymentDueDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_payment_receive_date"
     */
    public function testPropertyLastPaymentReceiveDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_payment_principal_amount"
     */
    public function testPropertyLastPaymentPrincipalAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_payment_interest_amount"
     */
    public function testPropertyLastPaymentInterestAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_payment_escrow_amount"
     */
    public function testPropertyLastPaymentEscrowAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_payment_last_fee_amount"
     */
    public function testPropertyLastPaymentLastFeeAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_payment_late_charge"
     */
    public function testPropertyLastPaymentLateCharge()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ytd_principal_paid"
     */
    public function testPropertyYtdPrincipalPaid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ytd_interest_paid"
     */
    public function testPropertyYtdInterestPaid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ytd_insurance_paid"
     */
    public function testPropertyYtdInsurancePaid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ytd_tax_paid"
     */
    public function testPropertyYtdTaxPaid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "auto_pay_enrolled"
     */
    public function testPropertyAutoPayEnrolled()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "margin_allowed"
     */
    public function testPropertyMarginAllowed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cash_account_allowed"
     */
    public function testPropertyCashAccountAllowed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "collateral"
     */
    public function testPropertyCollateral()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "current_school"
     */
    public function testPropertyCurrentSchool()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first_payment_date"
     */
    public function testPropertyFirstPaymentDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first_mortgage"
     */
    public function testPropertyFirstMortgage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_payment_freq"
     */
    public function testPropertyLoanPaymentFreq()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "original_school"
     */
    public function testPropertyOriginalSchool()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recurring_payment_amount"
     */
    public function testPropertyRecurringPaymentAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lender"
     */
    public function testPropertyLender()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ending_balance_amount"
     */
    public function testPropertyEndingBalanceAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_term_type"
     */
    public function testPropertyLoanTermType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payments_made"
     */
    public function testPropertyPaymentsMade()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "balloon_amount"
     */
    public function testPropertyBalloonAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "projected_interest"
     */
    public function testPropertyProjectedInterest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "interest_paid_ltd"
     */
    public function testPropertyInterestPaidLtd()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "interest_rate_type"
     */
    public function testPropertyInterestRateType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_payment_type"
     */
    public function testPropertyLoanPaymentType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "repayment_plan"
     */
    public function testPropertyRepaymentPlan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payments_remaining"
     */
    public function testPropertyPaymentsRemaining()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "margin_balance"
     */
    public function testPropertyMarginBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "short_balance"
     */
    public function testPropertyShortBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "available_cash_balance"
     */
    public function testPropertyAvailableCashBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "maturity_value_amount"
     */
    public function testPropertyMaturityValueAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vested_balance"
     */
    public function testPropertyVestedBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emp_match_amount"
     */
    public function testPropertyEmpMatchAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emp_pretax_contrib_amount"
     */
    public function testPropertyEmpPretaxContribAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emp_pretax_contrib_amount_ytd"
     */
    public function testPropertyEmpPretaxContribAmountYtd()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contrib_total_ytd"
     */
    public function testPropertyContribTotalYtd()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cash_balance_amount"
     */
    public function testPropertyCashBalanceAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pre_tax_amount"
     */
    public function testPropertyPreTaxAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "after_tax_amount"
     */
    public function testPropertyAfterTaxAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "match_amount"
     */
    public function testPropertyMatchAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "profit_sharing_amount"
     */
    public function testPropertyProfitSharingAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rollover_amount"
     */
    public function testPropertyRolloverAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "other_vest_amount"
     */
    public function testPropertyOtherVestAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "other_nonvest_amount"
     */
    public function testPropertyOtherNonvestAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "current_loan_balance"
     */
    public function testPropertyCurrentLoanBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_rate"
     */
    public function testPropertyLoanRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "buy_power"
     */
    public function testPropertyBuyPower()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rollover_ltd"
     */
    public function testPropertyRolloverLtd()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_award_id"
     */
    public function testPropertyLoanAwardId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "original_interest_rate"
     */
    public function testPropertyOriginalInterestRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "guarantor"
     */
    public function testPropertyGuarantor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "interest_subsidy_type"
     */
    public function testPropertyInterestSubsidyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "interest_balance"
     */
    public function testPropertyInterestBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "remaining_term_of_ml"
     */
    public function testPropertyRemainingTermOfMl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "initial_interest_rate"
     */
    public function testPropertyInitialInterestRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fees_balance"
     */
    public function testPropertyFeesBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_ytd_interest_paid"
     */
    public function testPropertyLoanYtdInterestPaid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_ytd_fees_paid"
     */
    public function testPropertyLoanYtdFeesPaid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_ytd_principal_paid"
     */
    public function testPropertyLoanYtdPrincipalPaid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_status"
     */
    public function testPropertyLoanStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_status_start_date"
     */
    public function testPropertyLoanStatusStartDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "loan_status_end_date"
     */
    public function testPropertyLoanStatusEndDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "weighted_interest_rate"
     */
    public function testPropertyWeightedInterestRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "repayment_plan_start_date"
     */
    public function testPropertyRepaymentPlanStartDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "repayment_plan_end_date"
     */
    public function testPropertyRepaymentPlanEndDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expected_payoff_date"
     */
    public function testPropertyExpectedPayoffDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "out_of_school_date"
     */
    public function testPropertyOutOfSchoolDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "convert_to_repayment"
     */
    public function testPropertyConvertToRepayment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "days_delinquent"
     */
    public function testPropertyDaysDelinquent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_principal_paid"
     */
    public function testPropertyTotalPrincipalPaid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_interest_paid"
     */
    public function testPropertyTotalInterestPaid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_amount_paid"
     */
    public function testPropertyTotalAmountPaid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
